### ISSUE TITLE
Functions Added To Interfaces Must Be A Major Version Bump

### ISSUE THREAD

**Issue by GrahamCampbell** [tomzx/php-semver-checker#10]

**Comment by tomzx** [comment]
Are methods added to an interface necessarily a major version bump?

From what I understand of semver, as long as you are not breaking anything (making incompatible API changes), a minor bump is good enough.

**Comment by GrahamCampbell** [comment]
If someone is implementing an interface and you add a method, you cause a php fatal error.

**Comment by drgomesp** [comment]
Well, if you add a new method to an interface you will most likely get that error before committing the source code, which means you either fix the issue by implementing the method or moving it to a different interface. I think its still not a major version bump.

**Comment by GrahamCampbell** [comment]
@drgomesp You're missing the point. If I have an interface that other people are using, I must not add methods to it. It will break their code. We MUST bump the major version.

**Comment by GrahamCampbell** [comment]
The fact that this requires a major version bump isn't up for discussion - it does. I'm reporting this as a missing check in this software.

**Comment by GrahamCampbell** [comment]
Also, changing the method signature of any method in an interface must be a major version bump too.

**Comment by GrahamCampbell** [comment]
We can't modify typehints or add params etc.

**Comment by tomzx** [comment]
@GrahamCampbell If you take a look at the [Ruleset](https://github.com/tomzx/php-semver-checker/blob/master/docs/Ruleset.md#interface), this is already covered by V035 and V036.

**Comment by GrahamCampbell** [comment]
Ok, cool. I'll take a look at that in more detail at the weekend. :)

**Comment by rquadling** [comment]
With regard to a non stable API (i.e. a V0.x.x), is a minor version bump the way to go when adding a new method to an interface?

**Comment by tomzx** [comment]
@rquadling From my understanding of the spec, while you're developing a non-stable API, what qualifies as a major bump should be a minor version bump until you want to turn the API into a stable version 1.0.0. However, since `php-semver-checker` is unaware of the current semantic version, it cannot suggest you a minor version bump.

However, if you use `php-semver-checker-git`, the `suggest` command will return a minor bump: https://github.com/tomzx/php-semver-checker-git/blob/master/src/PHPSemVerCheckerGit/Console/Command/SuggestCommand.php#L131:L141.
