### ISSUE TITLE
Why Do We Need Such A New Symfony Console?

### ISSUE THREAD

**Issue by GrahamCampbell** [tomzx/php-semver-checker#12]

**Comment by tomzx** [comment]
There's no particular reason. I generally tend to use cutting edge libraries.

I guess this could be changed to ~2.6 if stability is something we want. Maybe you have something better in mind?

**Comment by GrahamCampbell** [comment]
"~2.3" would make more sense, that is, if you're not using any of the newer stuff.

**Comment by tomzx** [comment]
Isn't ~2.3 pretty low? Why would we want to go that far into a past version? Is it related to the [Symfony LTS](http://symfony.com/doc/current/contributing/community/releases.html)?

**Comment by GrahamCampbell** [comment]
Yeh. 2.3 is still maintained.

**Comment by tomzx** [comment]
After taking a quick look, >=2.5 would be required since I make use of the `ProgressBar` class, which was introduced in 2.5.

I'm going to let this one sit a bit until I figure out what to do with it.

**Comment by GrahamCampbell** [comment]
You'll need `~2.5` then. :)

**Comment by Ninir** [comment]
Hey guys,

Having something for 2.3+ would we awesome until the Symfony2 LTS is over: there are people still using the LTS while semver-sionning their code! :)

**Comment by GrahamCampbell** [comment]
@Ninir We can't do 2.3. That's already decided. We can only do ~2.5.

**Comment by Ninir** [comment]
This is restraining a lot of usages... don't you think making a fallback, replacing the ProgressBar with something different in the UX could be done?

I agree it is annoying to maintain 2 versions (well in fact, it is an "if" in some places) but the symfony LTS will end around mid-2016...

**Comment by GrahamCampbell** [comment]
I don't see the real point tbh. People should just install this package on it's own if they really need to. Extra hacks would be pointless.

**Comment by mikeSimonson** [comment]
@Ninir Isn't that more logical to install this tool globally instead of in a precise project ?
Or maybe make a phar out of it ?

**Comment by Ninir** [comment]
This tool is really nice in the way it helps a lot to provide a near-perfect versionning: you have at least 2 opinions, yours and the tool one. A BC break is a regular thing when you maintain a basecode... this helps avoiding such thing.

If I want to install it AND i'm using a LTS framework/lib version that is requiring the `symfony/console` component, I just can't due to composer restrictions. 
It is not about extra hacks, it is just about making it available for the majority...

@mikeSimonson Yep! making a phar or installing it globally would be even better! :) I was just focusing on people relying on this dep directly from the project rather than having it globally ;)

**Comment by sagikazarmark** [comment]
I don't think the version really matters if you use the phar, which makes sense (and should be recommended). This is not something that you would require during the development, only at a very specific point. So it shouldn't affect your library's requirements.

**Comment by sagikazarmark** [comment]
Actually I wonder if it needs symfony console at all. If it only does comparison, it could do it with a simple PHP file (without any commands), using CLImate as an output formatter.

**Comment by Ninir** [comment]
It is somehow affecting my development as I am versionning my codebase. Adding a BC break in y code leads to a major version. Being omniscient on a code is a tough task, that's why having this kind of stuff on top of my tests, helps me to version in a better way. Do you get my point? :)

**Comment by sagikazarmark** [comment]
As I said, this tool shouldn't be part of the everyday development process. This is not a unit testing framework which you add in the development dependencies. While those are clearly part of the development (and every contributor should use the same), this is not. This is an external tool, which you use for versioning your software.

So I think that installing it a composer dependency should be the last thing you do. Also, using a phar is clearly a solution for your problem (using it with LTS versions). I get your point, but I think your problem does not really exist at all, since the solution is simply following the recommended way of using this tool. (Although I don't understand why isn't using the phar version is mentioned at all in the README as a recommendation)

**Comment by Ninir** [comment]
The tool is in charge of versionning a codebase by comparing 2 versions of it. It is not a unit testing framework, however, it is a codebase checking tool. Different tools for different purposes.

However, you're all right: a phar would be even better.

**Comment by sagikazarmark** [comment]
Exactly: different purpose, different usage.

**Comment by tomzx** [comment]
Does anyone have any additional issues regarding this? If not, I'll close this.

Considering #18 and the [README.md](https://github.com/tomzx/php-semver-checker/blob/master/README.md) instructions, it is clear that `php-semver-checker` shouldn't be installed as a composer dependency in projects (much like you wouldn't require composer in your projects).

Thus, it shouldn't matter too much which version of symfony's `Console` is used other than LTS related reasons as well as possibly supporting lower PHP versions (2.3 being 5.3.3, 2.7 being 5.3.9 and 3.0 being 5.5.9).

**Comment by sagikazarmark** [comment]
@tomzx Agreed :+1:

**Comment by Ninir** [comment]
@tomzx Sure :+1:

**Comment by GrahamCampbell** [comment]
Are we going with `~2.5` for now then?

**Comment by Ninir** [comment]
We do :)

**Comment by sagikazarmark** [comment]
> Thus, it shouldn't matter too much which version of symfony's `Console` is used...

If there is nothing in 2.6 which could probably be used in the near future, it could be 2.5, otherwise.....the latest the greatest.

**Comment by tomzx** [comment]
Since Symfony 2.7 is now LTS, that will be what is used.

However, after reflecting on the issue, it appears that the best course of action would be to separate the main logic from the CLI. This way, the only dependencies on this library would be `nikic/php-parser` while the CLI would have the remaining dependencies.

Although I do not think the main logic is of much interest alone, this would better separate the library's concern (and dependencies).

If anyone has further questions/discussion, please go ahead. I'm closing this for now.
