### ISSUE TITLE
Laravel

### ISSUE THREAD

**Issue by tomzx** [tomzx/php-semver-checker#36]
`A case analysis goal is to determine what work/doesn't work with php-semver-checker when it is applied on existing libraries/applications/frameworks. The purpose is to improve the quality of the output generated by php-semver-checker.`

**Comment by Anahkiasen** [comment]
Laravel didn't follow semver until 5.0 so it wouldn't be of much use in this case

**Comment by GrahamCampbell** [comment]
Laravel will never follow semver.

**Comment by Anahkiasen** [comment]
I thought I had heard Taylor say at Laracon that from 5 and on it would?

**Comment by GrahamCampbell** [comment]
Yeh, he's changed his mind. I talked to him a few weeks ago about this actually. We both agreed semantic versioning didn't suit laravel. He was concerned over Laravel's branding with major version bumps too.

**Comment by Anahkiasen** [comment]
Aw :( Man I thought this would be the year haters would stop being able to use that as an argument against Laravel not being business-friendly

**Comment by GrahamCampbell** [comment]
@Anahkiasen Imagine Laravel as following semver, only everything's offset, so instead of major versions for bc breaks and big stuff, we've got minor versions for that, and instead of having minor releases for new features, we're releasing smaller features into patch releases as well as bug fixes. Major version bumps will be reserved for much larger changes such as those found in 5.0, or indeed any bigger ones in the future.

**Comment by tomzx** [comment]
Since 5.1 was announced to "support" LTS, I'm going to start tracking changes. I've setup a private jenkins instance to test out changes to laravel/framework on an hourly basis and I'll see what I can do to make some of this information publicly available.
